export const lettershiragana = [
  { number: 1, name: "a", character: "あ" },
  { number: 2, name: "i", character: "い" },
  { number: 3, name: "u", character: "う" },
  { number: 4, name: "e", character: "え" },
  { number: 5, name: "o", character: "お" },
  { number: 6, name: "ka", character: "か" },
  { number: 7, name: "ki", character: "き" },
  { number: 8, name: "ku", character: "く" },
  { number: 9, name: "ke", character: "け" },
  { number: 10, name: "ko", character: "こ" },
  { number: 11, name: "sa", character: "さ" },
  { number: 12, name: "shi", character: "し" },
  { number: 13, name: "su", character: "す" },
  { number: 14, name: "se", character: "せ" },
  { number: 15, name: "so", character: "そ" },
  { number: 16, name: "ta", character: "た" },
  { number: 17, name: "chi", character: "ち" },
  { number: 18, name: "tsu", character: "つ" },
  { number: 19, name: "te", character: "て" },
  { number: 20, name: "to", character: "と" },
  { number: 21, name: "na", character: "な" },
  { number: 22, name: "ni", character: "に" },
  { number: 23, name: "nu", character: "ぬ" },
  { number: 24, name: "ne", character: "ね" },
  { number: 25, name: "no", character: "の" },
  { number: 26, name: "ha", character: "は" },
  { number: 27, name: "hi", character: "ひ" },
  { number: 28, name: "fu", character: "ふ" },
  { number: 29, name: "he", character: "へ" },
  { number: 30, name: "ho", character: "ほ" },
  { number: 31, name: "ma", character: "ま" },
  { number: 32, name: "mi", character: "み" },
  { number: 33, name: "mu", character: "む" },
  { number: 34, name: "me", character: "め" },
  { number: 35, name: "mo", character: "も" },
  { number: 36, name: "ya", character: "や" },
  { number: 36, name: "0", character: "0" },
  { number: 37, name: "yu", character: "ゆ" },
  { number: 36, name: "0", character: "0" },
  { number: 38, name: "yo", character: "よ" },
  { number: 39, name: "ra", character: "ら" },
  { number: 40, name: "ri", character: "り" },
  { number: 41, name: "ru", character: "る" },
  { number: 42, name: "re", character: "れ" },
  { number: 43, name: "ro", character: "ろ" },
  { number: 44, name: "wa", character: "わ" },
  { number: 36, name: "0", character: "0" },
  { number: 45, name: "wo", character: "を" },
  { number: 36, name: "0", character: "0" },
  { number: 46, name: "n", character: "ん" },
];
export const lettershiragana2 = [
  { number: 47, name: "ga", character: "が" },
  { number: 48, name: "gi", character: "ぎ" },
  { number: 49, name: "gu", character: "ぐ" },
  { number: 50, name: "ge", character: "げ" },
  { number: 51, name: "go", character: "ご" },

  { number: 52, name: "za", character: "ざ" },
  { number: 53, name: "ji", character: "じ" },
  { number: 54, name: "zu", character: "ず" },
  { number: 55, name: "ze", character: "ぜ" },
  { number: 56, name: "zo", character: "ぞ" },

  { number: 57, name: "da", character: "だ" },
  { number: 58, name: "ji2", character: "ぢ" },
  { number: 59, name: "zu2", character: "づ" },
  { number: 60, name: "de", character: "で" },
  { number: 61, name: "do", character: "ど" },

  { number: 62, name: "ba", character: "ば" },
  { number: 63, name: "bi", character: "び" },
  { number: 64, name: "bu", character: "ぶ" },
  { number: 65, name: "be", character: "べ" },
  { number: 66, name: "bo", character: "ぼ" },

  { number: 67, name: "pa", character: "ぱ" },
  { number: 68, name: "pi", character: "ぴ" },
  { number: 69, name: "pu", character: "ぷ" },
  { number: 70, name: "pe", character: "ぺ" },
  { number: 71, name: "po", character: "ぽ" },

  { number: 72, name: "kya", character: "きゃ" },
  { number: 73, name: "kyu", character: "きゅ" },
  { number: 74, name: "kyo", character: "きょ" },

  { number: 75, name: "sha", character: "しゃ" },
  { number: 76, name: "shu", character: "しゅ" },
  { number: 77, name: "sho", character: "しょ" },

  { number: 78, name: "cha", character: "ちゃ" },
  { number: 79, name: "chu", character: "ちゅ" },
  { number: 80, name: "cho", character: "ちょ" },

  { number: 81, name: "nya", character: "にゃ" },
  { number: 82, name: "nyu", character: "にゅ" },
  { number: 83, name: "nyo", character: "にょ" },

  { number: 84, name: "hya", character: "ひゃ" },
  { number: 85, name: "hyu", character: "ひゅ" },
  { number: 86, name: "hyo", character: "ひょ" },

  { number: 87, name: "mya", character: "みゃ" },
  { number: 88, name: "myu", character: "みゅ" },
  { number: 89, name: "myo", character: "みょ" },

  { number: 90, name: "rya", character: "りゃ" },
  { number: 91, name: "ryu", character: "りゅ" },
  { number: 92, name: "ryo", character: "りょ" },

  { number: 93, name: "gya", character: "ぎゃ" },
  { number: 94, name: "gyu", character: "ぎゅ" },
  { number: 95, name: "gyo", character: "ぎょ" },

  { number: 96, name: "ja", character: "じゃ" },
  { number: 97, name: "ju", character: "じゅ" },
  { number: 98, name: "jo", character: "じょ" },

  { number: 99, name: "bya", character: "びゃ" },
  { number: 100, name: "byu", character: "びゅ" },
  { number: 101, name: "byo", character: "びょ" },

  { number: 102, name: "pya", character: "ぴゃ" },
  { number: 103, name: "pyu", character: "ぴゅ" },
  { number: 104, name: "pyo", character: "ぴょ" },
];

export const letterskatakana = [
  { number: 1, name: "a", character: "あ" },
  { number: 2, name: "i", character: "い" },
  { number: 3, name: "u", character: "う" },
  { number: 4, name: "e", character: "え" },
  { number: 5, name: "o", character: "お" },
  { number: 6, name: "ka", character: "か" },
  { number: 7, name: "ki", character: "き" },
  { number: 8, name: "ku", character: "く" },
  { number: 9, name: "ke", character: "け" },
  { number: 10, name: "ko", character: "こ" },
  { number: 11, name: "sa", character: "さ" },
  { number: 12, name: "shi", character: "し" },
  { number: 13, name: "su", character: "す" },
  { number: 14, name: "se", character: "せ" },
  { number: 15, name: "so", character: "そ" },
  { number: 16, name: "ta", character: "た" },
  { number: 17, name: "chi", character: "ち" },
  { number: 18, name: "tsu", character: "つ" },
  { number: 19, name: "te", character: "て" },
  { number: 20, name: "to", character: "と" },
  { number: 21, name: "na", character: "な" },
  { number: 22, name: "ni", character: "に" },
  { number: 23, name: "nu", character: "ぬ" },
  { number: 24, name: "ne", character: "ね" },
  { number: 25, name: "no", character: "の" },
  { number: 26, name: "ha", character: "は" },
  { number: 27, name: "hi", character: "ひ" },
  { number: 28, name: "fu", character: "ふ" },
  { number: 29, name: "he", character: "へ" },
  { number: 30, name: "ho", character: "ほ" },
  { number: 31, name: "ma", character: "ま" },
  { number: 32, name: "mi", character: "み" },
  { number: 33, name: "mu", character: "む" },
  { number: 34, name: "me", character: "め" },
  { number: 35, name: "mo", character: "も" },
  { number: 36, name: "ya", character: "や" },
  { number: 36, name: "0", character: "0" },
  { number: 37, name: "yu", character: "ゆ" },
  { number: 36, name: "0", character: "0" },
  { number: 38, name: "yo", character: "よ" },
  { number: 39, name: "ra", character: "ら" },
  { number: 40, name: "ri", character: "り" },
  { number: 41, name: "ru", character: "る" },
  { number: 42, name: "re", character: "れ" },
  { number: 43, name: "ro", character: "ろ" },
  { number: 44, name: "wa", character: "わ" },
  { number: 36, name: "0", character: "0" },
  { number: 45, name: "wo", character: "を" },
  { number: 36, name: "0", character: "0" },
  { number: 46, name: "n", character: "ん" },
];

